export { default as ProvaiderAuth } from './ProvaiderAuth';
export { default as PrivateRouter } from './PrivateRouter';
export { default as ProvaiderConfig } from './ProvaiderConfig'
export { default as Modal } from './Modal'
export { default as LogoTag } from './LogoTag';
export { default as Tag} from './Tag'
export { default as HeardTag } from './HeardTag'
export { default as LineSector } from './LineSector'
export { default as FooterTag } from './FooterTag'
export { default as TagBody } from './TagBody'
export { default as TypeDoc } from './TypeDoc'
export { default as DocsDiv } from './DocsDiv'
export { default as BoxNumber} from './BoxNumber'
export { default as PageBody} from './PageBody'
export { default as  FormBack } from './FormBack'
export { default as FormLogin} from './FormLogin'
export { default as Inputs } from './Inputs'
export { default as Buttons } from './Buttons'
export { default as Selects } from './Selects'
export { default as ModalHeard} from './ModalHeard'
export { default as ButtonsIcons } from './ButtonsIcons'
export { default as ConteinnerUeps } from './ConteinnerUeps'
export {default as DivItem } from './DivItem'
export { default as TagUep } from './TagUep'
export { default as DivConnteiner } from './DivConnteiner'
export { default as ConnteinerDocs } from './ConnteinerDocs'